language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - CI_NAME=travis-ci
android:
  components:
  - android-22
  - build-tools-23.0.3
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew clean build jacocoTestReport coveralls"
after_success:
- bash <(curl -s https://codecov.io/bash)
