language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - CI_NAME=travis-ci

android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-25.0.2
    - sys-img-armeabi-v7a-android-22

cache:
  directories:
  - "$HOME/.gradle/caches/"

script:
  - "./gradlew clean build jacocoTestReport coveralls --info --stacktrace"
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &amp;
  - adb install -r trackertest/build/outputs/apk/trackertest-debug.apk
  - adb shell am start -n "io.ironsourceatom.trackertest/io.ironsourceatom.trackertest.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
 - bash <(curl -s https://codecov.io/bash)

