language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - CI_NAME=travis-ci

android:
  components:
    - platform-tools
    - tools
    - android-24
    - build-tools-25.0.2
    - sys-img-armeabi-v7a-android-24

cache:
  directories:
  - "$HOME/.gradle/caches/"

script:
  - "./gradlew clean build jacocoTestReport coveralls --info --stacktrace"
  - android-wait-for-emulator
  - adb devices
  - adb install trackertest/build/outputs/apk/trackertest-debug.apk
  - adb shell am start -W -n io.ironsourceatom.trackertest/io.ironsourceatom.trackertest.MainActivity -c android.intent.category.LAUNCHER
  - sleep 22
  - adb logcat -t 500 TrackerTest:D *:S > logcat.txt
  - sh tracker_test_status.sh

before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - android list targets
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
 - bash <(curl -s https://codecov.io/bash)

