language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - android-23
  - android-22
  - android-21
  - build-tools-23.0.0
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
#deploy:
#  provider: script
#  script: "./gradlew bintrayUpload"
#  on:
#    tags: true
