language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - CI_NAME=travis-ci
android:
  components:
  - platform-tools
  - tools
  - android-24
  - build-tools-25.0.2
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew clean build jacocoTestReport coveralls"
after_success:
- bash <(curl -s https://codecov.io/bash)
